tenants:
  NCP:
    devices:
      source: "file"   # netbox or nagios or "file"

      inventory_file: "devices.csv"

      nagios:
        hostgroups:
          - ConfigBackup_ios
          - ConfigBackup_nxos
      
      netbox:
        netbox_host: "netbox.example.com"
        netbox_token: "YOUR_NETBOX_TOKEN"


    credentials: # Credential file to access devices, usually tacacs cred
      credential_file: credentials

    vault:
      vault_address: https://localhost:8200
      approle_id_file: approle_id
      secret_id_file: approle_secretid
      breakglass-path: NCP/breakglass
      otp-path: NCP/otp